version: "3.9"
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
